config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments

    end

  root "posts#index"

  get '/about', to: 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  	  validates :name, presence: true,length: { minimum: 2 }
	  validates :body, presence: true,length: { minimum: 5 }
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments , dependent: :destroy
	  validates :title, presence: true,length: { minimum: 5 }
	  validates :body, presence: true,length: { minimum: 7 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment= @post.comments.create(comment_params)
		redirect_to post_path(@post)


		# @comment = @post.comments.new

		# if @comment.save
		# 	redirect_to post_path(@post)
			
		# else
		# 	render "/posts/#{params[:post_id]}/comments/new"

		# end

		
		
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
		
	end


	 private
    def comment_params
      params.require(:comment).permit(:name, :body)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except:[:index, :show]
	def index
		@posts=Post.all
	end

	def new
		@post= Post.new
		
	end
	def create
		@post =Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render "new"

		end
				
	end

	def show
		@post=Post.find(params[:id])
		
	end
	def edit
		@post=Post.find(params[:id])
		
	end

	def update
		@post =Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
			
		else
			render 'edit'
			
		end
		
	end

	def destroy
		@post=Post.find(params[:id])

		@post.destroy

		redirect_to posts_path
		
	end

	private
		def post_params
			params.require(:post).permit(:title,:body)
			
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name%></strong></p>
		<p class="comment_body"><%=comment.body%></p>
		<p class="comment_time"><%=time_ago_in_words(comment.created_at)%>ago</p>
		
	</div>
	<p>
	<%if user_signed_in?%>
		<%= link_to 'Delete',[comment.post ,comment],
			method: :delete,
			class:"button",
				data:{confirm:'Are U sure ?'}

		%>
		<% end -%>
	</p>
	__________________________________________________________________________
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f|%>

	<p>		
		<%=f.label :name %><br>
		<%=f.text_field  :name %>
	</p>
	<p>
		<%=f.label :body %><br>
		<%=f.text_area  :body %>	
		
	</p>
	<br>
	<p>
		<%=f.submit %>
	</p>




<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%=%>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
	<div id="logo">
		<%= link_to root_path do %>
			<%= image_tag("logo.jpg", height: '50', width: '50')%>
			<!-- <div> <h3><b> <font color="Green">My_Blog</font></b> <h3></div>	 -->
		<% end%>
	</div>
		<ul>
			<li class="category">Website</li>
			<li> <%= link_to "Myblog", root_path%></li>
			<li class="category"><%= link_to "About", about_path%></li>
		</ul>
		<ul>
			<li class="category">connect me</li>
			<li class="category"> <a href="https://www.facebook.com/ahmed99gouda">Facebook</a></li>
		</ul>
		<%if !user_signed_in? %>
			<p class="sign_in">Admin Login</p>
		<% end %>

	 </div>
	  <div id="main_content">
	  		<div id="header">
	  		<% if current_page?(root_path)%>
	  				<p>All posts</p>
	  		<%elsif current_page?(about_path)%>
	  				<p>About</p>
	  		<%else%>
	  				<p class="button"><%= link_to "Bake to all posts", root_path%></p>
	  		<%end%>	
	  		<%if user_signed_in?%>	
	  			<div class="buttons">
	  				<button class="button"><%=link_to "New Post" ,new_post_path %></button>
	  				<button class="button"><%= link_to "Logout",destroy_user_session_path ,:method => :delete%></button>

	  			</div>
	  			<%else%>
		  			<div class="buttons">
		  				<button class="button"><%=link_to "Login" ,new_user_session_path %></button>
		  				<button class="button"><%= link_to "sign up",new_user_session_path%></button>

		  			</div>

	  			<% end %>
	  		</div>
	  		
	  		<%= yield %>

	  		

	  </div>


</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">

	<div id="content">
		<h1>
			Wellcome to my new Ruby on rails Blog	
		</h1>	
		<p>
			<p>
					My Name is <strong> Ahmed gouda</strong>
			</p> 
			you can contact me go to CONNECT ME link on the side bar
		</p>	


	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%if @post.errors.any? %>
		<dir id="errors">
		<font color="red"><h2><%= pluralize(@post.errors.count ,"error") %></h2></font>
		<ul>
			<% @post.errors.full_messages.each do |msg|   %>
				<li><%=msg %></li>
			<% end %>
		</ul>	

		</dir>

	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field  :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area  :body %>
	</p>
	<p>
		<%= f.submit %><br>
		
	</p>

	
<% end%>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit Post</h1>

	<%= render 'form'%>
</div>

app/views/posts/index.html.erb
<!-- <h1>All Posts</h1>
 -->
<% @posts.each do |post|%>

<div class="post_wrapper">
	<h2  class="title">
		<%= link_to post.title, post%>
	</h2>

	<p class="body">
		

		<%= post.body %>
	</p>	
	<p  class="date" >
		
		 <font color="Cyan">published at <%= post.created_at.strftime("%B ,%d, %Y") %></font> 
		 <%if user_signed_in?%>
			<font color="blue"><%= link_to 'Edit', edit_post_path(post) %></font>
			<font color="red"><%= link_to 'Delete', post_path(post),
	              method: :delete,
	              data: { confirm: 'Are you sure?' } %></font>
	    <% end %>          
	</p>


</div>

<%end%>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>

	<%= render 'form'%>
</div>

app/views/posts/show.html.erb
<div id="page_wrapper">


	<h1 class="title">
		<font color="Green">
		<%=  @post.title%>
		</font>
	</h1>

		
	<p class="data">
		<font color="Cyan">
		submited <%= time_ago_in_words(@post.created_at) %> ago
		<%if user_signed_in?%>
			<font color="blue"><%= link_to 'Edit', edit_post_path(@post) %></font>
			<font color="red"><%= link_to 'Delete', post_path(@post),
	              method: :delete,
	              data: { confirm: 'Are you sure?' } %></font>
			</font>	
		<% end -%>	
	</p>
	<p class="body">
		

		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%=render @post.comments %>
		<%= render 'comments/form'%>
	</div>

	
</div>	